// ESLint flat config — generated by ci-partner skill (ESLint v9+)
// Stack: {{DETECTED_STACK}}
// Generated: {{DATE}}

import js from "@eslint/js";
import tseslint from "typescript-eslint";
{{ESLINT_PLUGIN_IMPORTS}}

/** @type {import('typescript-eslint').Config} */
export default tseslint.config(
  // Global ignores
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "dist/**",
      "build/**",
      "coverage/**",
      "*.config.{js,cjs,mjs}",
    ],
  },

  // Base JS rules
  js.configs.recommended,

  // TypeScript rules (type-checked)
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // Stack-specific plugins
  {{ESLINT_PLUGINS}},

  // Project-specific overrides
  {
    rules: {
      // TypeScript
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/consistent-type-imports": ["error", { prefer: "type-imports" }],

      // General
      "no-console": ["warn", { allow: ["warn", "error"] }],

      // Stack-specific
      {{ESLINT_RULES}}
    },
  },

  // Test file overrides
  {
    files: ["**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}", "**/__tests__/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  }
);
