/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as ReportIndexRouteImport } from './routes/report/index'
import { Route as ZonesIndexRouteImport } from './routes/zones/index'
import { Route as ZonesZoneIdRouteImport } from './routes/zones/$zoneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesIndexRoute = ZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesZoneIdRoute = ZonesZoneIdRouteImport.update({
  id: '/zones/$zoneId',
  path: '/zones/$zoneId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/zones/$zoneId': typeof ZonesZoneIdRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/report/': typeof ReportIndexRoute
  '/zones/': typeof ZonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/zones/$zoneId': typeof ZonesZoneIdRoute
  '/incidents': typeof IncidentsIndexRoute
  '/report': typeof ReportIndexRoute
  '/zones': typeof ZonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/zones/$zoneId': typeof ZonesZoneIdRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/report/': typeof ReportIndexRoute
  '/zones/': typeof ZonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/zones/$zoneId' | '/incidents/' | '/report/' | '/zones/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/zones/$zoneId' | '/incidents' | '/report' | '/zones'
  id:
    '__root__' | '/' | '/zones/$zoneId' | '/incidents/' | '/report/' | '/zones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ZonesZoneIdRoute: typeof ZonesZoneIdRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  ReportIndexRoute: typeof ReportIndexRoute
  ZonesIndexRoute: typeof ZonesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/': {
      id: '/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof ZonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/$zoneId': {
      id: '/zones/$zoneId'
      path: '/zones/$zoneId'
      fullPath: '/zones/$zoneId'
      preLoaderRoute: typeof ZonesZoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ZonesZoneIdRoute: ZonesZoneIdRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  ReportIndexRoute: ReportIndexRoute,
  ZonesIndexRoute: ZonesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
